I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 265, in script
    menu:
  File "game/script.rpy", line 289, in <module>
    "Can you tell me about this Mythology Book?" if MythologyBook in bag:
NameError: name 'MythologyBook' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 265, in script
    menu:
  File "C:\Users\Evan\Documents\Programming\RenPy\renpy-6.99.5-sdk\renpy\ast.py", line 1428, in execute
    choice = renpy.exports.menu(choices, self.set)
  File "C:\Users\Evan\Documents\Programming\RenPy\renpy-6.99.5-sdk\renpy\exports.py", line 725, in menu
    if renpy.python.py_eval(condition) ]
  File "C:\Users\Evan\Documents\Programming\RenPy\renpy-6.99.5-sdk\renpy\python.py", line 1477, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Evan\Documents\Programming\RenPy\renpy-6.99.5-sdk\renpy\python.py", line 1472, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 289, in <module>
    "Can you tell me about this Mythology Book?" if MythologyBook in bag:
NameError: name 'MythologyBook' is not defined

Windows-7-6.1.7601-SP1
Ren'Py 6.99.6.739
Mansion Test 0.0
